force-app/main/default/objects/Account/fields/GH_dte_FechaTerminoCredencializacion__c.field-meta.xml
<CustomField>
    <fullName>GH_dte_FechaTerminoCredencializacion__c</fullName>
    <defaultValue>(TODAY() + 7)</defaultValue>
    <description>Campo para credencialización.</description>
    <label>Fecha termino credencializacion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/GH_pkl_EstadodelMedico__c.field-meta.xml
<CustomField>
    <fullName>GH_pkl_EstadodelMedico__c</fullName>
    <description>Para credencialización</description>
    <label>Estado del Médico</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <label>✔️ Activo</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
                <label>❌ Inactivo</label>
            </value>
            <value>
                <fullName>Inactivo_por_baja</fullName>
                <label>❌ Inactivo por baja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GH_pkl_EstadodePrivilegios__c.field-meta.xml
<CustomField>
    <fullName>GH_pkl_EstadodePrivilegios__c</fullName>
    <description>Para credencialización</description>
    <label>Estado de Privilegios</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Con Privilegios</fullName>
                <label>✔️ Con Privilegios</label>
            </value>
            <value>
                <fullName>Sin Privilegios</fullName>
                <label>❌ Sin Privilegios</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
                <label>❌ Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GH_pkl_Estatus__c.field-meta.xml
<CustomField>
    <fullName>GH_pkl_Estatus__c</fullName>
    <description>Campo para credencialización.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En Solicitud</fullName>
            </value>
            <value>
                <fullName>En Proceso</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>❌ Cancelado</label>
            </value>
            <value>
                <fullName>Privilegios Completo o Incompleto</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
                <label>✔️ Aprobado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <label>❌ Rechazado</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GH_pkl_Origen__c.field-meta.xml
<CustomField>
    <fullName>GH_pkl_Origen__c</fullName>
    <defaultValue>IF( OR($UserRole.DeveloperName  =&apos;Ejecutivo_de_Ventas_Cel_UH&apos;,$UserRole.DeveloperName =&apos;Jefe_de_Ventas_Cel_UH&apos;),&apos;Transitorio&apos;,&apos;&apos;)</defaultValue>
    <label>Tipo de Credencialización Inicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Permanente</fullName>
            </value>
            <value>
                <fullName>Temporal</fullName>
            </value>
            <value>
                <fullName>Transitorio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GH_Account_TriggerHandler_test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class GH_Account_TriggerHandler_test {

    @isTest
    static void updateAccount() {
        Account oAcc = new Account();
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GH_PAc_CredencializacionInicial').getRecordTypeId();
        oAcc.FirstName = 'PUBLICO';
        oAcc.LastName = 'GENERAL';
        oAcc.RecordTypeId = rtId;
        oAcc.GH_pkl_EstadodelMedico__c = 'Activo';
        oAcc.GH_pkl_EstadodePrivilegios__c = 'Con Privilegios';
        oAcc.GH_dte_FechaTerminoCredencializacion__c = date.valueOf('3027-11-30');
        oAcc.GH_pkl_Origen__c = 'Permanente';
        oAcc.GH_pkl_Estatus__c = 'Aprobado';
        insert oAcc;
        oAcc.LastName = 'GENERALL';
        update oAcc;
    }
}